### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by levilliard** [Ybalrid/Qt5Ogre21#2]
Hi,
Can you make this works on Android ?

**Comment by Ybalrid** [comment]
There are fundamental problems with running Ogre 2.x on Android that would make attempting to put Ogre 2 rendering inside a Qt widget on Android pointless...

http://wiki.ogre3d.org/tiki-index.php?page=Ogre+2.1+FAQ#Is_there_Android_Support_

As far as I know, the GLES 3 renderer for Ogre 2 isn't usable yet.

You should look into the Ogre 1.x branch for Android.
